<?php
/*
*@file
*This file contain hooks and other global functions.
*/

// Menu for my page
function formsmodule_menu () {
    $items = [];
    $items['formsmodule'] = array(
        'title' => 'Forms Page',
        'page callback' => 'drupal_get_form',
        'menu_name' => 'main-menu',
        'page arguments' => ['formsmodule_form'],
        'access callback' => 'user_is_logged_in', // access only for authenticated user
    );

    return $items;
}
// Here im creating forms for this page
function formsmodule_form ($form, &$form_state) {
    $form['markup']['#markup'] = format_string('<h2>@markup</h2>', ['@markup' => t('Who are you in Drupal')]);

    // task3 - checkbox
    $form ['checkboxForm'] = [
        '#type' => 'checkbox',
        '#title' => t('Do you like drupal? '),
    ];
    // task4 - checkboxes
    $form['checkboxesForm'] = [
        '#type' => 'checkboxes',
        '#title' => t('What versions of drupal did you used?'),
        '#options' => [
            '6' => '6',
            '7' => '7',
            '8' => '8',
            '9' => '9'
        ],
        '#required' => TRUE,
    ];
     //task5 - machine_name
    // Sorry but i dont know how to fix this form, exists always back a warning
    $form['machine_nameForm'] = [
        '#type' => 'machine_name',
        '#maxlenght' => 15,
        '#default_value' => 'machine_nameform',
        '#machine_name' => [
            'exists' => 'menu_edit_machine_nameForm_exists',
        ],
    ];
    // task6 - selected
    $form['selectedForm'] = [
        '#type' => 'select',
        '#title' => t('How long do you programming?'),
        '#options' => ['0-2', '3-5', '5-10', '10+'],
        '#description' => t('It is an important information for this page'),
        '#required' => TRUE,
        '#default_value' => '0-2',
    ];
    // task7 - textarea
    $form['textareaForm'] = [
        '#type' => 'textarea',
        '#title' => t('Describe yourself as a programmer'),
        '#description' => t(
            'The comment will be unpublished if it contains any of the phrases above. 
             Use a case-sensitive, comma-separated list of phrases. 
             Example: funny, bungee jumping, "Company, Inc."
             .<em>Thanks for description drupal.org</em> '
        ),
        '#required' => TRUE,
    ];
    // task8 - textfield
    $form['textfieldForm'] = [
        '#type' => 'textfield',
        '#title' => t('What do you think about this information forms?'),
        '#size' => 60,
        '#maxlength' => 128,
        '#description' => t('Describe in a few words'),
        '#required' => TRUE,
    ];
    // And it is a button to submit all info in this page
    $form ['save'] = [
        '#type' => 'submit',
        '#value' => t('Confirm your answers'),
    ];

    return $form;
}

function formsmodule_form_validate ($form, &$form_state) {
    // Validate some info of different forms and set an error
    if (mb_strlen($form_state['values']['textareaForm']) < 5 ) {
        form_set_error( 'textareaForm', t('That\'s all you can describe about yourself? Please write more!'));
    }
    if ($form_state['values']['textfieldForm'] == t('worst') ) {
        form_set_error( 'textfieldForm', t('Why do you think so? Try again'));
    }
    if (
        $form_state['values']['checkboxesForm'][9]
        && $form_state['values']['checkboxesForm'][6] == 0
        && $form_state['values']['checkboxesForm'][7] == 0
        && $form_state['values']['checkboxesForm'][8] == 0
    ) {
        form_set_error('checkboxesForm', t('How did you used only 9 version?'));
    }
}
// Here, the program will send several messages depending on the answers
function formsmodule_form_submit ($form, &$form_state) {
    if ($form_state['values']['checkboxForm'] == 1) {
        drupal_set_message(t('Nice! Drupal community <3 with you'), 'status', FALSE);
    }
    /* It is a bad practice to write same, but i had some troubles with this arrays, so it was the easiest way
    * Here i am checking if the user likes a drupal and used all versions of drupal, so user will get a message,
    * that he is a Dries Buytaert
    */
    if (
        $form_state['values']['checkboxesForm'][6]
        && $form_state['values']['checkboxesForm'][7]
        && $form_state['values']['checkboxesForm'][8]
        && $form_state['values']['selectedForm'] == 3
        && $form_state['values']['checkboxForm'] == 1
    ) {
        drupal_set_message(t('Hello, <a href="https://dri.es/">Dries Buytaert</a>! Nice to meet you'), 'status', FALSE);
    }
    if ($form_state['values']['textfieldForm'] == 'nice') {
        drupal_set_message(t('Thanks for your answers'), 'status', FALSE);
    }
    if ($form_state['values']['checkboxesForm'][8]) {
        drupal_set_message(t('8 version will provide a big future for drupal and us'), 'status', FALSE);
    }
    if ($form_state['values']['selectedForm'] == 0) {
        drupal_set_message(t('You are in a right way!'), 'status', FALSE);
    }

}

